### ISSUE TITLE
pdb_sync fails with AttributeError (NoneType)

### ISSUE THREAD

**Issue by paravoid** [peeringdb/django-peeringdb#17] opened 2017-10-25 07:49 UTC
```
org last update 0 11326 changed
data to be processed 11326
fac last update 0 2586 changed
data to be processed 2586
net last update 0 10964 changed
data to be processed 10964
ix last update 0 624 changed
data to be processed 624
ixfac last update 0 1243 changed
data to be processed 1243
ixlan last update 0 622 changed
data to be processed 622
ixpfx last update 0 983 changed
data to be processed 983
poc last update 0 16110 changed
data to be processed 16110
netfac last update 0 19418 changed
data to be processed 19418
netixlan last update 0 21342 changed
data to be processed 21342
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/paravoid/venv/peeringdb/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/paravoid/venv/peeringdb/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/paravoid/venv/peeringdb/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/paravoid/venv/peeringdb/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/paravoid/venv/peeringdb/lib/python3.5/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 89, in handle
    self.sync(tables, pk, limit=limit)
  File "/home/paravoid/venv/peeringdb/lib/python3.5/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 96, in sync
    self.update_db(cls, self.get_objs(cls, pk=pk, **kwargs))
  File "/home/paravoid/venv/peeringdb/lib/python3.5/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 175, in update_db
    self._sync(cls, row)
  File "/home/paravoid/venv/peeringdb/lib/python3.5/site-packages/django_peeringdb/management/commands/pdb_sync.py", line 144, in _sync
    sync.sync_obj(cls, row)
  File "/home/paravoid/venv/peeringdb/lib/python3.5/site-packages/django_peeringdb/sync.py", line 52, in sync_obj
    setattr(obj, field.name, value)
  File "/home/paravoid/venv/peeringdb/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 437, in __set__
    setattr(rel_obj, self.related.field.name, None)
AttributeError: 'NoneType' object has no attribute 'netixlan'
```

I just reproduced this in a clean Python3 environment with just `pip install django django-peeringdb` ran in it. Full environment is:
```
certifi==2017.7.27.1
chardet==3.0.4
Django==1.11.6
django-countries==5.0
django-handleref==0.3.0
django-inet==0.3.2
django-peeringdb==0.7.0
idna==2.6
ipaddress==1.0.18
pkg-resources==0.0.0
pytz==2017.2
requests==2.18.4
six==1.11.0
twentyc.rpc==0.4.0
urllib3==1.22
```

**Comment by vegu** [comment] 2017-10-25 09:09
Thanks for the report, does it insert any objects in peeringdb_network_ixlan at all?

**Comment by paravoid** [comment] 2017-10-25 09:20
Nope. Adding try/except: pass to that line makes it import at least some networks, although I have reasons to suspect not all of them.

**Comment by vegu** [comment] 2017-10-25 10:16
Not having much luck reproducing, what database are you using?

```
./manage.py pdb_sync
org last update 0 11329 changed
data to be processed 11329
fac last update 0 2586 changed
data to be processed 2586
net last update 0 10967 changed
data to be processed 10967
ix last update 0 624 changed
data to be processed 624
ixfac last update 0 1243 changed
data to be processed 1243
ixlan last update 0 622 changed
data to be processed 622
ixpfx last update 0 983 changed
data to be processed 983
poc last update 0 3276 changed
data to be processed 3276
netfac last update 0 19420 changed
data to be processed 19420
netixlan last update 0 21349 changed
data to be processed 21349
```

completes without error

thats on `Python 3.5.1` with

```
certifi==2017.7.27.1
chardet==3.0.4
Django==1.11.6
django-countries==5.0
django-handleref==0.3.0
django-inet==0.3.2
django-peeringdb==0.7.0
idna==2.6
pytz==2017.2
requests==2.18.4
six==1.11.0
twentyc.rpc==0.4.0
urllib3==1.22
```

in the virtualenv, writing to a `sqlite3` db, i will try with mysql as well in a bit

**Comment by paravoid** [comment] 2017-10-25 10:47
This was with a sqlite3 db, Python 3.5.3 and with an app with concrete models. Weird!

**Comment by paravoid** [comment] 2017-10-25 10:55
New virtualenv set up with:
```
python3 -m venv foo
. foo/bin/activate
pip install django django-peeringdb
```

Then in the checkout of my project (https://github.com/paravoid/peerassist), with a settings.py with an sqlite3 database, `PEERINGDB_SYNC_STRIP_TZ = True` and without `PEERINGDB_ABSTRACT_ONLY` defined, I ran:
```
python3 ./manage.py migrate
python3 ./manage.py migrate --run-syncdb
python3 ./manage.py pdb_sync
```

I already reproduced it three times but I'll try re-running it shortly, just in case it was transient. Are you sure you're using Python3? `manage.py` has a `/usr/bin/env python` shebang, which in most distributions points to Python 2.

**Comment by paravoid** [comment] 2017-10-25 11:24
Yup, still the same. I added a print, and it seems that it barfs on 12322's Equinix Ashburn object. I haven't added a try/except yet though, so that may (and will probably) be the case for other netixlans as well -- that was just the first occurence.

**Comment by vegu** [comment] 2017-10-25 11:30
> Are you sure you're using Python3? manage.py has a /usr/bin/env python shebang, which in most distributions points to Python 2.

Yea, however just to be sure, i am running it now with `python3.5 manage.py pdb_sync`, will report back with results shortly

**Comment by vegu** [comment] 2017-10-25 11:40
Finished without error :/

Interestingly, if it's failing on netixlan 12322 thats just adding another layer of weirdness, because thats marked as deleted and should not even be synced to a fresh database in the first place.

**Comment by vegu** [comment] 2017-10-25 11:43
So to clarify, https://github.com/paravoid/peerassist is the project where this is failing in ? I could try checking that out and see about reproducing in there.

**Comment by vegu** [comment] 2017-10-25 11:47
Pretty sure for some reason its not playing nice with the netixlan property that is set up here: https://github.com/paravoid/peerassist/blob/master/peercollect/models.py

**Comment by paravoid** [comment] 2017-10-25 11:48
Sorry, I meant AS12322, not the object with id 12322.

I think I'm getting closer to the reason, though; `field.name` in this case seems to be "peering", which incidentally is a model defined in my app as:
```
from django_peeringdb.models.concrete import NetworkIXLan

@python_2_unicode_compatible
class Peering(models.Model):
    netixlan = models.OneToOneField(NetworkIXLan, db_index=True)
    router = models.CharField(max_length=255, db_index=True)

    def __str__(self):
        return "Peering with {} on {}".format(
                self.netixlan.net.name,
                self.netixlan.ixlan.ix.name
            )
```

So, this explains why you're not seeing this. I don't see anything wrong with my definition, though, so it's a bit puzzling why this happens,

**Comment by vegu** [comment] 2017-10-25 12:01
> Sorry, I meant AS12322, not the object with id 12322.

No worries, at least its not trying to sync a deleted object :)

In line 52 in sync.py during the logic that syncs each field

```
            if hasattr(ftyp, "related_name") and ftyp.multiple:
                continue
```

This is supposed to skip relationships (they are sync'd via the respective _id fields if i recall correctly). However i am not sure i recall why we only skip on ftyp.multiple fields, which is why it's probably trying to sync the peering backref from the onetoone field. Could try dropping the ftyp.multiple check and see what that does.

**Comment by paravoid** [comment] 2017-10-25 12:14
So, my model has a one-to-one relationship with model `NetIXLan`. This means that it would show up in `cls._meta.get_fields()`, which `sync_obj()` iterates on.

(Side note: that function looks quite off: a) it does a `ftyp = cls._meta.get_field(field.name)` which I think is redundant, as `field` is already that and thus `ftyp == field`, and b) it has a `return` statement, then has more code after that, probably a previous version of the code or something?)

Therefore, it eventually does a `setattr(obj, field.name, value)`, which is essentially `obj.peering = None` on an empty database. This works, but if you try (e.g. on a shell) to do:
```
getattr(obj, 'peering', None)
setattr(obj, 'peering', None)
```
…it fails with the same error. It looks like Django is trying to set the inverse relationship, and fails for some reason? What is that code's purpose anyway? Why does it skip on `ftyp.multiple`?

**Comment by vegu** [comment] 2017-10-25 12:20
Yeah that function definitely needs some cleanup, looking at it some more, the syncing of the values actually happens above, the second loop through the fields just seems to take care of stripping the tzinfo of datetime fields and then just re-setting the values of the fields, apparently not really doing anything.

And yea, the code past the return, seems to be cruft that needs to be thrown out.

**Comment by vegu** [comment] 2017-10-25 12:30
As a side node since it says it can't find the "netixlan" property in the error. I wonder where that's coming from, only thing i can see is the __str__ method on your model. Can you try changing that to something that doesnt ref self.netixlan and see if that changes the error message?

**Comment by paravoid** [comment] 2017-10-25 12:46
`related_name` would be empty in a OneToOneRel so that fix wouldn't work. `related_model` would exist, so I can try replacing the hasattr with that and see if that works.

`netixlan` comes from the name of the field, pointing to the reverse relationship. In the one-to-one relationship (Peering having a OneToOneField to NetworkIXLan), `obj.peering == rel_obj` and `rel_obj.netixlan == obj`.

Note that this is all reproducible in a `./mange.py shell` with:
```
obj = NetworkIXLan()
getattr(obj, 'peering', None) [or obj.peering]
setattr(obj, 'peering', None) [or obj.peering = None]
```
…and doesn't trigger without the `getattr()`. This really is starting to feel like a Django bug?

**Comment by vegu** [comment] 2017-10-25 13:10
Hm, i see, that does sound like django is accepting to set peering to None on the netixlan but then also tries to set netixlan on the None value as if it's a Peering instance.

**Comment by paravoid** [comment] 2017-10-25 13:54
I think the root cause is a Django bug, so I filed it as https://code.djangoproject.com/ticket/28742. We can and probably should mitigate its effect here, though.

**Comment by vegu** [comment] 2017-10-25 16:47
> We can and probably should mitigate its effect here, though.

Agreed

**Comment by paravoid** [comment] 2017-11-17 16:51
Ping? :)

**Comment by grizz** [comment] 2017-11-21 06:31
@paravoid finally getting to this, sorry for the delay. We're checking into this and will report back ASAP

**Comment by grizz** [comment] 2017-11-23 07:05
@paravoid that function had an embarrassing amount of cruft, thanks for pointing it out

**Comment by grizz** [comment] 2017-11-26 16:27
@paravoid did this fix it for you?

**Comment by XioNoX** [comment] 2017-11-27 20:44
That solved the issue for me.

**Comment by grizz** [comment] 2017-12-07 08:04
Thanks

**Closed by grizz** 2017-12-07 08:04 UTC
